export const typography = {
  h1: {
    fontFamily: 'Roboto',
    fontSize: 30,
    lineHeight: 42,
    fontWeight: '700' as const,
    letterSpacing: -0.5,
  },
  h2: {
    fontFamily: 'Roboto',
    fontSize: 26,
    lineHeight: 36,
    fontWeight: '700' as const,
    letterSpacing: -0.5,
  },
  h3: {
    fontFamily: 'Roboto',
    fontSize: 22,
    lineHeight: 34,
    fontWeight: '700' as const,
    letterSpacing: -0.4,
  },
  subheading: {
    fontFamily: 'Roboto',
    fontSize: 18,
    lineHeight: 28,
    fontWeight: '700' as const,
    letterSpacing: -0.4,
  },
  title1: {
    fontFamily: 'Roboto',
    fontSize: 16,
    lineHeight: 26,
    fontWeight: '700' as const,
    letterSpacing: -0.4,
  },
  title2: {
    fontFamily: 'Roboto',
    fontSize: 14,
    lineHeight: 24,
    fontWeight: '700' as const,
    letterSpacing: -0.3,
  },
  title3: {
    fontFamily: 'Roboto',
    fontSize: 12,
    lineHeight: 20,
    fontWeight: '700' as const,
    letterSpacing: -0.3,
  },
  body1: {
    fontFamily: 'Roboto',
    fontSize: 12,
    lineHeight: 20,
    fontWeight: '400' as const,
    letterSpacing: -0.3,
  },
  body1Long: {
    fontFamily: 'Roboto',
    fontSize: 12,
    lineHeight: 22,
    fontWeight: '400' as const,
    letterSpacing: -0.3,
  },
  body2: {
    fontFamily: 'Roboto',
    fontSize: 10,
    lineHeight: 18,
    fontWeight: '400' as const,
    letterSpacing: -0.3,
  },
  body2Long: {
    fontFamily: 'Roboto',
    fontSize: 10,
    lineHeight: 18,
    fontWeight: '400' as const,
    letterSpacing: -0.3,
  },
  caption: {
    fontFamily: 'Roboto',
    fontSize: 8,
    lineHeight: 12,
    fontWeight: '400' as const,
    letterSpacing: -0.2,
  },
} as const;

export type TypographyVariant = keyof typeof typography;
